### ISSUE TITLE
[Colab] Error on first cell

### ISSUE THREAD

**Issue by albrrt** [titsitits/open-image-restoration#1]
Hello,

Thank you for sharing this toolkit for image restoration.

I tried running the Google Colab but couldn't pass the first cell for uploading an image.
It returns the following error:

```
ERROR: nbclient 0.5.0 has requirement jupyter-client>=6.1.5, but you'll have jupyter-client 5.3.5 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-cfc620a77232> in <module>()
     32 
     33   os.chdir(repodir)
---> 34   import ImagePipeline_utils as IP
     35   import ImageRestorer
     36   restorer = ImageRestorer.ImageRestorer()

1 frames
/usr/local/lib/python3.6/dist-packages/PIL/ImageDraw.py in <module>()
     35 
     36 from . import Image, ImageColor
---> 37 from ._util import isStringType
     38 
     39 """

ImportError: cannot import name 'isStringType'
```

Is it possible to solve this problem?

Thank you

**Comment by titsitits** [comment]
Hi, that's new indeed!

I just checked, it seems that the version of pillow freezed in the requirements.txt file is no more compatible with google colab default environment.

It seems to work with the latest version of pillow (7.2 as time of writing).
I just updated the requirements.txt file, so it should be working now.

Thank you for reporting the bug!

**Comment by albrrt** [comment]
Hi, thank you for the quick response! It works now
